buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "net.serenity-bdd:serenity-gradle-plugin:4.2.22"
        classpath "net.serenity-bdd:serenity-single-page-report:4.2.22"
    }
}

plugins {
    id 'buildlogic.java-common-conventions'
}

apply plugin: "net.serenity-bdd.serenity-gradle-plugin"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

defaultTasks 'clean', 'test', 'aggregate'

ext {
    serenity_version = "4.2.22"
    cucumber_version = "7.22.0"
    junit_version = "5.12.2"
    logback_classic_version="1.5.18"
    assertj_core_version="3.23.1"
}

dependencies {
    testImplementation project(":serenity-playwright-extension")

    testImplementation platform("org.junit:junit-bom:${junit_version}")
    testImplementation platform("io.cucumber:cucumber-bom:${cucumber_version}")

    testImplementation "net.serenity-bdd:serenity-core:${serenity_version}"
    testImplementation "net.serenity-bdd:serenity-cucumber:${serenity_version}"
    testImplementation "net.serenity-bdd:serenity-screenplay:${serenity_version}"
    // testImplementation "net.serenity-bdd:serenity-screenplay-webdriver:${serenity_version}"
    testImplementation "net.serenity-bdd:serenity-screenplay-playwright:${serenity_version}"
    testImplementation "net.serenity-bdd:serenity-ensure:${serenity_version}"
    testImplementation "org.junit.platform:junit-platform-launcher"
    testImplementation "io.cucumber:cucumber-junit-platform-engine"
    testImplementation "org.junit.platform:junit-platform-suite"
    testImplementation "org.junit.jupiter:junit-jupiter-engine"
    // testImplementation "org.junit.vintage:junit-vintage-engine:${junit_vintage_engine_version}"
    implementation "ch.qos.logback:logback-classic:${logback_classic_version}"
    testImplementation "ch.qos.logback:logback-classic:${logback_classic_version}"
    testImplementation "org.assertj:assertj-core:${assertj_core_version}"
}

serenity {
    reports = ["single-page-html"]
}

gradle.startParameter.continueOnFailure = true

test.finalizedBy(aggregate, reports)

tasks.named("checkOutcomes").configure {
    dependsOn "reports"
}
